### ISSUE TITLE
Feature Request: Display what required "special characters" are

### ISSUE THREAD

**Issue by cwendt01** [strangerstudios/pmpro-strong-passwords#1]
Overall this plugin works great! I have ran into one issue though since deploying it: Users who try to register are not sure what "special characters" are when creating their passwords. A lot of my users have been trying to use underscores as that 1 required special character, but this plugin and WordPress do not consider that to be "special" enough.

According to WP, the actual special characters that it requires are as follows: !@#$%^&*() 

> source: http://codex.wordpress.org/Function_Reference/wp_generate_password 

My request is to include the list of special characters in the "A strong password requires..." text that gets added to the sign-up forms. This way people who are signing-up don't have to guess multiple times until they hit the right special character.

I know how to custom code this in myself since I'm a programmer, but have this pre-built into the code will definitely help a lot of non-programmers in the future!

Thanks,
- C.

**Comment by andrewlimaza** [comment]
Thanks for this, I know this ticket is old. We're moving to use the default WP Strength password calculator/indicator.
