### ISSUE TITLE
not like any other strong password

### ISSUE THREAD

**Issue by grifini** [strangerstudios/pmpro-strong-passwords#22]
![pass](https://user-images.githubusercontent.com/50019105/65766046-23fa6800-e12a-11e9-832c-e42117b32494.jpg)

and this is a huge drawback. People get tried of trying or adding new characters at the end.  It keeps asking for a special character though it is already added. Strangely, in several attempts it says medium for a 9 letter password and when you add one more it goes back to weak and no matter how many characters you add it stays there.

**Comment by andrewlimaza** [comment]
Thank you for bringing this to our attention, please can you ensure your password includes one or more of the following:

Special character, lowercase character, uppercase character and numbers. Please let me know if this helps.

Please can you try with a variation of passwords or test passwords by including special characters in the front of your password and some passwords with these at the end. The question mark next to the password will let you know what kind of characters are needed as well.

I hope this helps, please keep me posted.

**PS: Please do not post actual passwords here but generate dummy passwords for testing purposes and let me know if you find any commonality for this not to show "strong" and stay on "medium" strength.**

**Comment by grifini** [comment]
Andrew,
Thanks for your reply. You are a one of those people that I know I can rely on when I need a solid support. 
I have all, including an uppercase, lowercase, special character and a number in my password trials. One thing I realized from my many trials is that some special characters are not recognized as a "special character" by this addon (it keeps asking for a special character). Besides, sometimes with a valid special character when the password is accepted, it is still shown as weak though all conditions are met. Then users still think that they don't met the requirements and kept adding more.

**Comment by andrewlimaza** [comment]
Thanks for the feedback, would you mind telling me what special characters are failing so we may look into this further?

**Comment by grifini** [comment]
Underscore fails. Others I don't remember now.

**Comment by grifini** [comment]
It is still not working.

**Comment by andrewlimaza** [comment]
We are still fine-tuning this script to support more special characters. Thank you for your patience.

**Comment by andrewlimaza** [comment]
You may try the pre-release - https://github.com/strangerstudios/pmpro-strong-passwords/tree/dev

**Comment by mircobabini** [comment]
Fixed in release 0.4.
