### ISSUE TITLE
Consider adding a filter for the minimum amount of characters required for a strong password

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-strong-passwords#27]
The minimum required characters for a strong password is set at 8 characters. It could be beneficial to consider adding a filter allowing to set a custom required password length.

As a workaround, this is currently possible replacing the existing filter here:
https://github.com/strangerstudios/pmpro-strong-passwords/blob/cf6ea506422e27e2d9347b263f1df7d8fd527765/pmpro-strong-passwords.php#L63-L127

**Comment by andrewlimaza** [comment]
Leaving this one open, looking into filtering this for the library we started using.  Filter has been added for our custom checker function (Sites on older PHP versions).

**Comment by andrewlimaza** [comment]
Okay so this is being added into next update - `pmprosp_minimum_password_length` and return a lower amount. However, you would need to also filter the `pmprosp_minimum_password_score` for PHP 7.2+ using the zxcvbn library to allow weaker passwords and don't throw an error if a medium/weak password is used.
