### ISSUE TITLE
Confusing weak check on password2

### ISSUE THREAD

**Issue by mircobabini** [strangerstudios/pmpro-strong-passwords#28]
You have already checked the password strength on password field, then you just have to check the match/mismatch on password2, not re-calculating the progress bar. It doesn't make any sense and it's confusing.

**Comment by andrewlimaza** [comment]
Hey @mircobabini we're working on a fix for this, there is a pre-release on the `dev` branch that should do this.

**Comment by mircobabini** [comment]
Fixed in release 0.4
