### ISSUE TITLE
PMPro Strong Passwords Library - Bump Minimum PHP Requirement?

### ISSUE THREAD

**Issue by ronalfy** [strangerstudios/pmpro-strong-passwords#35]
For those on older versions of PHP, this ZIP should work for you while we patch the plugin.

[pmpro-strong-passwords.zip](https://github.com/strangerstudios/pmpro-strong-passwords/files/5196901/pmpro-strong-passwords.zip)

Developers:

The issue is the library dropped PHP < 7.3 support in this release: https://github.com/bjeavons/zxcvbn-php/releases/tag/1.0.0

The latest is: https://github.com/bjeavons/zxcvbn-php/releases/tag/1.1.0

**Comment by mircobabini** [comment]
Seems like they fixed it: https://github.com/bjeavons/zxcvbn-php/commit/f13e90c97d84329bf6bd24f24857eecb3dd02f38

Now support is 7.2+.

**Comment by andrewlimaza** [comment]
Thanks @mircobabini
