### ISSUE TITLE
PHP error thrown when sign up and taking a membership level at once

### ISSUE THREAD

**Issue by skotperez** [strangerstudios/pmpro-strong-passwords#39]
The error is the following:

    `PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in wp-content/plugins/pmpro-strong-passwords/vendor/bjeavons/zxcvbn-php/src/Matcher.php on line 10

My server config:
Linux Debian
PHP 7.0
MySQL 5.5.62

Once the pmpro-strong-passwords extension is deactivated, the error is gone and the sign up process completes smoothly.

**Comment by mircobabini** [comment]
The bjeavons/zxcvbn-php dependency supports PHP 7.2+.

**Comment by andrewlimaza** [comment]
This has been updated to load our custom checker for sites running older versions than 7.2 for the zxcvbn library. This should be included in the next release - https://github.com/strangerstudios/pmpro-strong-passwords/commit/77e7fbd75cd39d93e68a2a8910fbe323b4b6b47a
