### ISSUE TITLE
BUG: Javascript password hint tooltip rendered incorrectly when containing a double quotation

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-strong-passwords#40]
When a password tooltip contains a double quotation mark (`"`) the JavaScript rendered tooltip breaks from the point where the double quotation is encountered.

*To Recreate*

1. Install & activate PMPro Require Strong Passwords Add On.
2. Navigate to the front-end PMPro checkout page and hover the mouse pointer over the `?` after the Password field label.

![210304-1614862176](https://user-images.githubusercontent.com/9744519/109967148-ba589300-7cf9-11eb-88ba-cc939c4880fa.png)

![210304-1614862391](https://user-images.githubusercontent.com/9744519/109967181-c6445500-7cf9-11eb-8af8-f1ac74103878.png)

A temporary workaround is to filter the password hint:

```php
function my_pmprosp_password_hint( $password_hint ) {
	if ( function_exists( 'pmpro_strong_password_check' ) ) {
		$password_hint = str_replace( '"', '', $password_hint ); // remove double quote that causes issues with javascript tooltip.
	}
	return $password_hint;
}
add_filter( 'password_hint', 'my_pmprosp_password_hint' );
```

**Comment by andrewlimaza** [comment]
We now use the default WordPress wp_password_hint method. I think the issue would be with WordPress itself.

**Comment by andrewlimaza** [comment]
Tested this and it should no longer cause an issue. Closing this issue.
