### ISSUE TITLE
Make password character length (12) filterable

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-strong-passwords#41]
We should allow developer's to filter the length of required password, some site owners may want passwords with a length of 9 characters for example.

Code Ref: https://github.com/strangerstudios/pmpro-strong-passwords/blob/dev/pmpro-strong-passwords.php#L141

**Comment by mircobabini** [comment]
The PR makes it filterable for PHP < 7.

This gist permits to define the length for PHP >= 7 as well: https://gist.github.com/mircobabini/41f6ab7a0c6d2b2284b3fafc30441ce9
