### ISSUE TITLE
We should localize the strings in the error messages in the zxcvbn library.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/pmpro-strong-passwords#49]
There may be other strings shown to users, but there are a couple in here:
https://github.com/strangerstudios/pmpro-strong-passwords/blob/4c683441d04fe52f7690a916fcbbde630a0c842b/vendor/bjeavons/zxcvbn-php/src/Feedback.php

If the WP site running this add on is not in English, these words will show up untranslated.

Wrapping these strings in __()/etc for WP could work, but then it would be hard to update this library without having to redo that work. (That might be worth it. I don't know how often this library is updated.)

Another option would be to update the plugin to get the responses from the library and then compare them and swap them with localized versions. This way, translations would still work if the library was updated... unless new strings were introduced somehow. Then we'd have to update our code to handle them.

So it would be like:

`
$suggestions = $password_strength['feedback']['suggestions'];
foreach( $suggestions as $key => $text ) {
   if( $text === 'Add another word or two. Uncommon words are better.' ) {
     $suggestions[$key] = __( 'Add another word or two. Uncommon words are better.', 'pmpro-strong-passwords' );
   }
}
`

Here is where the message is set: https://github.com/strangerstudios/pmpro-strong-passwords/blob/dev/pmpro-strong-passwords.php#L112

There is a filter there already (pmprosp_minimum_password_score_message). But it would be good to not require custom code for these translations.

**Comment by ideadude** [comment]
Gist using the existing filter. Could be a work around until we get to this. https://gist.github.com/ideadude/778e66b566b800c6a19d34e472a1e856

**Comment by kimcoleman** [comment]
This is resolved in https://github.com/strangerstudios/pmpro-strong-passwords/pull/56 and going out today.
