### ISSUE TITLE
Translation fails for feedbacks

### ISSUE THREAD

**Issue by tiicaa** [strangerstudios/pmpro-strong-passwords#50]
I am trying to translate the sequential messages: `<div id="pmpro_message" class="pmpro_message pmpro_error">Password Error: Add another word or two. Uncommon words are better. Avoid sequences</div>`

Using the Loco Translate plugin, I have already translated all the terms but this message simply does not exist for translation and I could not even launch a script then to force translation by means of the .pmpro_message .pmpro_error classes because they are used for other feedbacks. How can I solve this?

**Comment by andrewlimaza** [comment]
Thanks for creating this issue @tiicaa, we are looking into this for a future release. You can look at this related issue for the time being which has a temporary fix - https://github.com/strangerstudios/pmpro-strong-passwords/issues/49#issuecomment-1338225988

**Comment by kimcoleman** [comment]
This is resolved in https://github.com/strangerstudios/pmpro-strong-passwords/pull/56 and going out today.
