### ISSUE TITLE
Tooltip hint data-tooltip attribute HTML rendered incorrectly.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-strong-passwords#52]
**Describe the bug**
When hovering over the `?` to display the password hint tooltip, the tooltip text string in the `data-tooltip` attribute ends with the first occurrence of a double quote and the remaining characters thereafter are rendered as attributes, e.g. `symbols like ! " ?="" $="" %="" ^="" &="" )."="">?</span>`

Original string:

`Hint: The password should be at least twelve characters long. To make it stronger, use upper and lower case letters, numbers, and symbols like ! " ? $ % ^ & ).`

Rendered HTML:

```html
<span class="pmprosp-tooltip__password" data-tooltip-location="right" data-tooltip="Hint: The password should be at least twelve characters long. To make it stronger, use upper and lower case letters, numbers, and symbols like ! " ?="" $="" %="" ^="" &="" )."="">?</span>
```
Displayed string:

`Hint: The password should be at least twelve characters long. To make it stronger, use upper and lower case letters, numbers, and symbols like ! `

**Additional Notes**

The password hint is obtained using the `wp_get_password_hint()` and passed to the JavaScript using the `wp_localize_script` here:

https://github.com/strangerstudios/pmpro-strong-passwords/blob/cb0591e31fd0606efcd8be4a7e34e918fa72a2ec/pmpro-strong-passwords.php#L49

Using the `password_hint` filter available for the `wp_get_password_hint()` function to replace a double quote `"` with either the equivalent name or hex HTML entity does not resolve this while replacing any variant of the double quote with two single quotes does.

For example:

```PHP
function password_hint_replace_double_quotes( $password_hint ) {
	return str_replace( array( '&#34;', '&quot;', '"' ), "''", $password_hint );
}
add_filter( 'password_hint', 'password_hint_replace_double_quotes' );
```
As an alternative method, one can look at correcting this in the javascript file by adding a `replace(/"/g, '&quot;')` call to `pwsL10n.password_tooltip`.

https://github.com/strangerstudios/pmpro-strong-passwords/blob/cb0591e31fd0606efcd8be4a7e34e918fa72a2ec/js/jquery.pmpro-strong-passwords.js#L27

```javascript
jQuery('.pmpro_checkout-field-password label').append('<span class="pmprosp-tooltip__password" data-tooltip-location="right" data-tooltip="' + pwsL10n.password_tooltip.replace(/"/g, '&quot;') + '">?</span>');
```

**To Reproduce**
1. Go to checkout page and hover mouse pointer over the `?` next to password label.
2. View incomplete text string.
3. View page source and locate `span` element with class `pmprosp-tooltip__password`.

**Screenshots**

![2024-06-22_08-53-42](https://github.com/strangerstudios/pmpro-strong-passwords/assets/9744519/065def39-3d0f-4fe1-a4cd-0769e2c3c61c)

**Expected behavior**
The tooltip HTML is rendered correctly and the text string is displayed in full.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kimcoleman** [comment]
This is fixed in https://github.com/strangerstudios/pmpro-strong-passwords/pull/53/commits/e5df4f91a3899bc228ee72d49a029b5abd6c3a33
