### ISSUE TITLE
BUG: Name Fields placed before password strength notification when using pmpro-add-name-to-checkout

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-strong-passwords#6]
When using pmpro-addname-to-checkout, the name fields are displayed before the password strength message and as such the password strength message is wrongly displayed after the name fields instead of after password fields.

A workaround would be to add a priority here https://github.com/strangerstudios/pmpro-strong-passwords/blob/32de411710d112c5c5d9b60cecbc0a72466a995c/pmpro-strong-passwords.php#L82

`add_filter( "pmpro_checkout_after_password", "pmprosp_pmpro_checkout_after_password", 1 );`

**Comment by andrewlimaza** [comment]
This has been resolved.
